name: ${project.name}
description: ${project.description}
version: ${project.version}
author: zPedroo_
main: com.zpedroo.medals.Main
softdepend: [ProtocolLib, HolographicDisplays]
commands:
  medals:
    aliases: [medalha, medalhas]